### PR TITLE
Update Mansalva

### PR DESCRIPTION
**Pull request by emmamarichal**
Hello Carolina!

Here you can find the modifications of the repo, to follow the Google's specs :)
It took time because we had a technical issue we had to solve, sorry about that! 

Otherwise, the font was well exported and the alternate work. Please check if all seem good to you. 
Don't hesitate if you have any questions!

Also, can you complete this description? 

> "Mansalva is a handwritten font which works well for notes and informal passages of text. It features many alternate OpenType characters which makes text appear more handwritten and less mechanical."

This is the text that will appear on the Google font specimen page, and it would be nice if you could write something about this big update :) (just one or two sentences can be enough!)

Thanks a lot, 
Emma

### CODE REVIEW

**Comment by carolinashort** [comment]
Hello Emma!

Thanks for your help and comments, all looks good to me. 

For the description, is there a document to update? Or is it ok to paste it here?

Mansalva is a script font that works well for notes and informal text passages. Presents two alternates for each letter and number to provide a natural, handwritten, less mechanical look. It features good legibility for a handwriting typeface and is perfect for a casual-looking annotation. Latest updates include a Latin Plus language coverage currently supporting most Latin-based languages.

[feel free to edit if too long]

Thanks heaps,
Carolina

**Comment by emmamarichal** [comment]
That's perfect, thanks :)

**Comment by emmamarichal** [comment]
Hello @carolinashort! 
I would probably send you a new PR with a small change about metrics (we don't have the same result as the GF version), so I have to fix that :)

But before that, I saw you made some modifications on the sources in your repo. What is it? Can I merge them safely?
Thanks :)

**Comment by carolinashort** [comment]
Yes, It might have been just a small change I did in the kerning for Māori (Ng pair)
Thanks!

**Pull request merged**
